CREATE TABLE CARRO 
( 
 ID CARRO INT PRIMARY KEY,  
 MODELO INT,  
 COR INT,  
); 

CREATE TABLE COMPRADOR 
( 
 ID COMPRADOR INT PRIMARY KEY,  
 CARTAO INT,  
 IDADE INT,  
); 

CREATE TABLE CONCESSIONARIA 
( 
 ID LOJA INT PRIMARY KEY,  
 CNPJ INT,  
); 

CREATE TABLE TEM 
( 
 ID CARRO INT PRIMARY KEY,  
 ID COMPRADOR INT PRIMARY KEY,  
); 

CREATE TABLE VENDE 
( 
 ID LOJA INT PRIMARY KEY,  
 ID COMPRADOR INT PRIMARY KEY,  
); 

CREATE TABLE TEM1 
( 
 ID LOJA INT PRIMARY KEY,  
 ID CARRO INT PRIMARY KEY,  
); 

ALTER TABLE TEM ADD FOREIGN KEY(ID CARRO) REFERENCES CARRO (ID CARRO)
ALTER TABLE TEM ADD FOREIGN KEY(ID COMPRADOR) REFERENCES COMPRADOR (ID COMPRADOR)
ALTER TABLE VENDE ADD FOREIGN KEY(ID LOJA) REFERENCES CONCESSIONARIA (ID LOJA)
ALTER TABLE VENDE ADD FOREIGN KEY(ID COMPRADOR) REFERENCES COMPRADOR (ID COMPRADOR)
ALTER TABLE TEM1 ADD FOREIGN KEY(ID LOJA) REFERENCES CONCESSIONARIA (ID LOJA)
ALTER TABLE TEM1 ADD FOREIGN KEY(ID CARRO) REFERENCES CARRO (ID CARRO)
